### ISSUE TITLE
Allow hiding schema fields when calling toJSON

### ISSUE THREAD

**Issue by reaktivo** [Automattic/mongoose#1020]
This is a feature request to allow hiding of a schema field when converting the document into json. I'm not sure if it would be better if this was set from inside the schema declaration or from the toJSON call, e.g.

```
user = new Schema
  username: 
    type: String
  password:
    type: String
    expose: false
```

or something like 

```
User.findOne({username: 'joe'}, function(err, doc) {
  user = doc.toJSON(hide: 'password')
});
```
