### ISSUE TITLE
can't connect to mongodb in docker

### ISSUE THREAD

**Issue by metrocoding** [Automattic/mongoose#10962]
I made a docker image of node and MongoDB database and I'm using mongoose v6
I can connect to the database but when I set username and password for the database I can't connect to it and get error:
```
server_1  | MongoServerError: Authentication failed.
server_1  |     at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:467:30)
server_1  |     at MessageStream.emit (node:events:390:28)
server_1  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
server_1  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
server_1  |     at writeOrBuffer (node:internal/streams/writable:390:12)
server_1  |     at _write (node:internal/streams/writable:331:10)
server_1  |     at MessageStream.Writable.write (node:internal/streams/writable:335:10)
server_1  |     at Socket.ondata (node:internal/streams/readable:777:22)
server_1  |     at Socket.emit (node:events:390:28)
server_1  |     at addChunk (node:internal/streams/readable:324:12) {
server_1  |   ok: 0,
server_1  |   code: 18,
server_1  |   codeName: 'AuthenticationFailed'
server_1  | }
```

this is my docker-compose section:
```
    server:
        depends_on:
            - db
        restart: unless-stopped
        build: ./server
        ports:
            - 3001:3001
        environment:
            DB_URL: mongodb://username:xMYjMawxUkn8PabK@db:27017/mydb
        command: ./docker-entrypoint.sh
        networks:
            - server
            - frontend

    db:
        image: mongo:5.0.3
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: xMYjMawxUkn8PabK
            MONGO_INITDB_DATABASE: mydb
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - lotto360:/data/db
        networks:
            - server
```
