### ISSUE TITLE
nodejs app container can't connect to Mongodb Container (docker) 

### ISSUE THREAD

**Issue by asdin2015** [Automattic/mongoose#11195]
i'm beginner in mongodb/mongoose. im building simple fullstack project. I'm using nodejs(api), react/nginx and mongodb as database server. The connection to mongodb works using machine ip and doesn't work when i use service name  'mongodb' (look to docker-compose.yml) .

peace of node js app code:
```
...
 // connection doesn't work
mongoose.connect("mongodb://user:pass@mongodb:27027/yps?authSource=admin")
.then(() => console.log('MongoDB connected'))
.catch(err  => console.log(err));
...
```

```
...

// connection works
mongoose.connect("mongodb://user:pass@192.168.1.100:27027/yps?authSource=admin")
.then(() => console.log('MongoDB connected'))
.catch(err  => console.log(err));
...

```

docker-compose.yml

```

version: "3"

services:
        backend:
                container_name: backend
                build:
                  context: ./api
                ports:
                  - "3001:3001"
                networks:
                  - tesNet
                volumes:
                  - ./api:/app:ro
                links:
                  - mongodb
        mongodb:
                container_name: mongo
                image: mongo:5.0.2
                restart: always
                ports:
                        - "27027:27017"
                networks:
                        - tesNet
                volumes:
                        - /var/lib/docker/volumes/mongodb2.backup:/data/bak
                        - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/mongo-init.sh
                        - /var/lib/docker/volumes/mongodb2.data:/data/db
                environment:
                        - MONGO_INITDB_DATABASE=yps
                        - MONGO_INITDB_ROOT_USERNAME=user
                        - MONGO_INITDB_ROOT_PASSWORD=pass
        frontend:
                container_name: frontend
                build:
                  context: ./client
                ports:
                  - "8080:80"
                networks:
                  - yaskawanet
                depends_on:
                    - backend
networks:
        tesNet:
```

Error
```
| MongooseServerSelectionError: connect ECONNREFUSED 172.23.0.2:27027
at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:797:32)
at /app/node_modules/mongoose/lib/index.js:332:10
at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
at new Promise (<anonymous>)
at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1158:10)
at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:331:20)
at Object.<anonymous> (/app/build/src/main.js:48:20)
at Module._compile (node:internal/modules/cjs/loader:1097:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10) {
reason: TopologyDescription {
type: 'Unknown',
**servers: Map(1) { 'mongodb:27027' => [ServerDescription] },**
stale: false,
compatible: true,
heartbeatFrequencyMS: 10000,
localThresholdMS: 15,
logicalSessionTimeoutMinutes: undefined
}
}
```

### Information

  - mongodb v5.0.2,
  - docker v20.10.7
  - nodejs: alpine
  - nginx latest
  - reactjs 17.0.2
