### ISSUE TITLE
Mongoose client not reconnecting to primary Mongo replica after replica election 

### ISSUE THREAD

**Issue by austinconry** [Automattic/mongoose#12846]
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.6.0

### Node.js version

14.20.1

### MongoDB version

4.4.5

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Debian Bullseye Slim

### Issue

Mongo: 4.4.5
Mongoose: 6.6.0
Node: 14.20.1 (bullseye-slim)
Docker: 20.10.8

## Problem
We have a docker swarm with multiple servers and a mongo stack with 3 replicas each on different servers. 
Our rs1(primary) replica goes down due to a Docker restart.  When this happens an election occurs and rs3 is selected as the new primary.  After rs1 is re-elected a few seconds later, some of our backend client replicas receive the following error when making queries:

```
MongooseServerSelectionError: Server selection timed out after 30000 ms
    at Function.Model.$wrapCallback (/usr/share/backend-server/node_modules/mongoose/lib/model.js:5192:32)
    at /usr/share/backend-server/node_modules/mongoose/lib/query.js:4901:21
    at /usr/share/backend-server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/usr/share/backend-server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at model.Query.exec (/usr/share/backend-server/node_modules/mongoose/lib/query.js:4900:10)
    at model.Query.Query.then (/usr/share/backend-server/node_modules/mongoose/lib/query.js:4983:15) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'rs1:27017' => [ServerDescription],
      'rs2:27017' => [ServerDescription],
      'rs3:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxElectionId: new ObjectId("7fffffff0000000000000053"),
    maxSetVersion: 1,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: 30
  },
  code: undefined
}
```

Upon checking the status of the replicas, rs1 is the primary and most of our backend clients fulfill queries correctly. We have seen this issue occur on two separate occasions and we are unsure why some Mongoose clients are unable to find the primary replica after the election. We have been unable to recreate the error intentionally. 

### docker-compose.yml: 
The image being used is for Mongodb 4.4.5

```yaml
version: '3.3'
secrets:
  mongo_cluster_key:
    external: true
services:
  rs1:
    image: mongodb-custom:v1.0.0
    command: mongod --keyFile /run/secrets/mongo_cluster_key --replSet "rs0"
    networks:
      - mongo
    ports:
      - 27017:27017
    secrets:
      - source: mongo_cluster_key
        target: mongo_cluster_key
        uid: '999'
        gid: '999'
        mode: 0400
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin 
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=admin
    - MAIN_MONGO_DB_NAME=testing
    - MAIN_MONGO_DB_USERNAME=test
    - MAIN_MONGO_DB_PASSWORD=password
    - MAIN_MONGO_DB_ROLE=readWrite
    deploy:
      replicas: 1
    volumes:
      - rs1:/data/db 
      - rs1:/data/configdb
  rs2:
    image: mongodb-custom:v1.0.0
    command: mongod --keyFile /run/secrets/mongo_cluster_key --replSet "rs0"
    networks:
      - mongo
    secrets:
      - source: mongo_cluster_key
        target: mongo_cluster_key
        uid: '999'
        gid: '999'
        mode: 0400
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin 
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=admin
    - MAIN_MONGO_DB_NAME=testing
    - MAIN_MONGO_DB_USERNAME=test
    - MAIN_MONGO_DB_PASSWORD=password
    - MAIN_MONGO_DB_ROLE=readWrite
    deploy:
      replicas: 1
    volumes:
      - rs2:/data/db 
      - rs2:/data/configdb
  rs3:
    image: mongodb-custom:v1.0.0
    command: mongod --keyFile /run/secrets/mongo_cluster_key --replSet "rs0"
    networks:
      - mongo
    secrets:
      - source: mongo_cluster_key
        target: mongo_cluster_key
        uid: '999'
        gid: '999'
        mode: 0400
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin 
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=admin
    - MAIN_MONGO_DB_NAME=testing
    - MAIN_MONGO_DB_USERNAME=test
    - MAIN_MONGO_DB_PASSWORD=password
    - MAIN_MONGO_DB_ROLE=readWrite
    deploy:
      replicas: 1
    volumes:
      - rs3:/data/db 
      - rs3:/data/configdb
  rs:
    image: mongodb-custom:v1.0.0
    command: /usr/local/bin/replica-init.sh
    networks:
      - mongo
    secrets:
      - source: mongo_cluster_key
        target: mongo_cluster_key
        uid: '999'
        gid: '999'
        mode: 0400
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin 
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=admin
    - MAIN_MONGO_DB_NAME=testing
    - MAIN_MONGO_DB_USERNAME=test
    - MAIN_MONGO_DB_PASSWORD=password
    - MAIN_MONGO_DB_ROLE=readWrite
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
volumes:
  rs1:
    driver: local
  rs2:
    driver: local
  rs3:
    driver: local
networks:
  mongo:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: true
    attachable: true
```

### replica-init.sh: 

```sh
#!/bin/bash
# Make sure 3 replicas available
for rs in rs1 rs2 rs3;do
  mongo --host $rs --eval 'db'
  if [ $? -ne 0 ]; then
    exit 1
  fi
done
MONGO_INITDB_ROOT_USERNAME="$(< $MONGO_INITDB_ROOT_USERNAME_FILE)"
MONGO_INITDB_ROOT_PASSWORD="$(< $MONGO_INITDB_ROOT_PASSWORD_FILE)"
# Connect to rs1 and configure replica set if not done
status=$(mongo --host rs1 --quiet --eval 'rs.status().members.length')
if [ $? -ne 0 ]; then
  # Replicaset not yet configured
  mongo --username $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --host rs1 --eval 'rs.initiate({ _id: "rs0", version: 1, members: [ { _id: 0, host : "rs1", priority: 100 }, { _id: 1, host : "rs2", priority: 2 }, { _id: 2, host : "rs3", priority: 2 } ] })';
fi
```

### backend-server.js

```js
const mongoose = require('mongoose');
// MongoDB Connection Class
class MongoDB {
  constructor() {
    mongoose
      .connect('mongodb://test:password@rs1:27017,rs2:27017,rs3:27017/testing?replicaSet=rs0')
      .then(() => {
        console.log('Connected to MongoDB');
      })
      .catch((err) => {
        console.error('MongoDB Error: ', err.message);
      });
    // Add error handler while connected
    mongoose.connection.on('error', (err) => {
      console.log('MongoDB Error: ', err);
    });
    mongoose.pluralize(null);
  }
}
module.exports = new MongoDB();
```

We have 2500 connections, between 60 clients, so using the directConnection flag may be too slow.

## What we've tried
1. We have tested the replica election process and it seems to be electing a secondary node as the new primary correctly once the original primary goes down.  It also is re-electing the original primary once that node comes back up. 
2. We have verified that the priorities for each primary and secondary node are set correctly.  
3. The Docker Swarm DNS resolves rs1's hostname and is reachable from the backend server container that has a Mongoose client receiving the error above.  

We verified that the authentication and connection strings are all setup correctly.  When this error occurs, restarting the backend server docker containers fixes the issue.  We are not receiving any connection errors in our backend server logs.  Errors only appear when querying the database.

**Comment by vkarpov15** [comment]
Can you please provide the contents of `reason.servers` in your original error?

```
servers: Map(3) {
      'rs1:27017' => [ServerDescription],
      'rs2:27017' => [ServerDescription],
      'rs3:27017' => [ServerDescription]
    },
```

That may help.

Also, do the server selection timeouts persist? Or do the services go back to normal after some time has passed?

**Comment by austinconry** [comment]
Unfortunately we don't have the ServerDescription object. That was all we are able to capture from the error.  The server selection timeouts persist until the backend server containers that are getting this error are manually restarted.

**Comment by AustinMutschler** [comment]
Are all of your clients Mongoose clients?

**Comment by austinconry** [comment]
No about half of our clients are using PyMongo from a separate service (pymongo==3.12.2, flask-pymongo==0.5.2).  None of the PyMongo clients were having this issue.

**Comment by vkarpov15** [comment]
We'll give this a shot, but realistically without more details the odds are low that we'll be able to repro this.

**Comment by austinconry** [comment]
@vkarpov15 We were able to consistently recreate the problem using 10 backend-server replicas. 
## Steps to recreate

- With the three Mongo nodes(rs1, rs2, rs3) running, we scale down rs1 to 0 so that the domain name becomes unresolvable in the backend-server containers. 
- We scaled rs1 back up to 1 and that is when a subset of the backend-servers begin to get the ServerSelection timeout error when making queries. 

We were able to capture the ServerDescription coming from the containers that aren't working. 

## ServerDescription.json

```json
{
  "rs1:27017": {
    "address": "rs1:27017",
    "type": "RSSecondary",
    "hosts": ["rs1:27017", "rs2:27017", "rs3:27017"],
    "passives": [],
    "arbiters": [],
    "tags": {},
    "minWireVersion": 0,
    "maxWireVersion": 9,
    "roundTripTime": 3.2,
    "lastUpdateTime": 986361255,
    "lastWriteDate": "2023-01-03T18:10:42.000Z",
    "error": null,
    "topologyVersion": {
      "processId": "63b46f8c266fb96988dd2c27",
      "counter": 5
    },
    "setName": "rs0",
    "setVersion": 1,
    "electionId": "7fffffff0000000000000111",
    "logicalSessionTimeoutMinutes": 30,
    "primary": "rs1:27017",
    "me": "rs1:27017",
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": "7184490055728103425"
      },
      "signature": {
        "hash": "K3zn4JZzngXlzxYPoj+tZzSDAdA=",
        "keyId": {
          "low": 1,
          "high": 1664341472,
          "unsigned": false
        }
      }
    }
  },
  "rs2:27017": {
    "address": "rs2:27017",
    "type": "RSSecondary",
    "hosts": ["rs1:27017", "rs2:27017", "rs3:27017"],
    "passives": [],
    "arbiters": [],
    "tags": {},
    "minWireVersion": 0,
    "maxWireVersion": 9,
    "roundTripTime": 2.201506860187476,
    "lastUpdateTime": 986421573,
    "lastWriteDate": "2023-01-03T18:11:45.000Z",
    "error": null,
    "topologyVersion": {
      "processId": "63accd0268d01ce7aff71693",
      "counter": 104
    },
    "setName": "rs0",
    "setVersion": 1,
    "electionId": null,
    "logicalSessionTimeoutMinutes": 30,
    "primary": "rs1:27017",
    "me": "rs2:27017",
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": "7184490317721108481"
      },
      "signature": {
        "hash": "ILMiahI8q557Csqe5m2XlzFq1Fw=",
        "keyId": {
          "low": 1,
          "high": 1664341472,
          "unsigned": false
        }
      }
    }
  },
  "rs3:27017": {
    "address": "rs3:27017",
    "type": "RSSecondary",
    "hosts": ["rs1:27017", "rs2:27017", "rs3:27017"],
    "passives": [],
    "arbiters": [],
    "tags": {},
    "minWireVersion": 0,
    "maxWireVersion": 9,
    "roundTripTime": 2.8756552296142996,
    "lastUpdateTime": 986421560,
    "lastWriteDate": "2023-01-03T18:11:45.000Z",
    "error": null,
    "topologyVersion": {
      "processId": "63accd02c733a8254923b641",
      "counter": 44
    },
    "setName": "rs0",
    "setVersion": 1,
    "electionId": null,
    "logicalSessionTimeoutMinutes": 30,
    "primary": "rs1:27017",
    "me": "rs3:27017",
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": "7184490317721108481"
      },
      "signature": {
        "hash": "ILMiahI8q557Csqe5m2XlzFq1Fw=",
        "keyId": {
          "low": 1,
          "high": 1664341472,
          "unsigned": false
        }
      }
    }
  }
}
```

Here is the rs.status() at the time that these errors are ocurring.

## rs.status()
```js
{
  set: 'rs0',
  date: 2023-01-03T18:18:44.991Z,
  myState: 1,
  term: Long("273"),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long("2000"),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1672769915, i: 1 }), t: Long("273") },
    lastCommittedWallTime: 2023-01-03T18:18:35.064Z,
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1672769915, i: 1 }), t: Long("273") },
    readConcernMajorityWallTime: 2023-01-03T18:18:35.064Z,
    appliedOpTime: { ts: Timestamp({ t: 1672769915, i: 1 }), t: Long("273") },
    durableOpTime: { ts: Timestamp({ t: 1672769915, i: 1 }), t: Long("273") },
    lastAppliedWallTime: 2023-01-03T18:18:35.064Z,
    lastDurableWallTime: 2023-01-03T18:18:35.064Z
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1672769905, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'priorityTakeover',
    lastElectionDate: 2023-01-03T18:10:44.973Z,
    electionTerm: Long("273"),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 1672769442, i: 1 }), t: Long("272") },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1672769442, i: 1 }), t: Long("272") },
    numVotesNeeded: 2,
    priorityAtElection: 100,
    electionTimeoutMillis: Long("10000"),
    priorPrimaryMemberId: 1,
    numCatchUpOps: Long("0"),
    newTermStartDate: 2023-01-03T18:10:45.046Z,
    wMajorityWriteAvailabilityDate: 2023-01-03T18:10:46.054Z
  },
  members: [
    {
      _id: 0,
      name: 'rs1:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 504,
      optime: [Object],
      optimeDate: 2023-01-03T18:18:35.000Z,
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1672769444, i: 1 }),
      electionDate: 2023-01-03T18:10:44.000Z,
      configVersion: 1,
      configTerm: 273,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'rs2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 490,
      optime: [Object],
      optimeDurable: [Object],
      optimeDate: 2023-01-03T18:18:35.000Z,
      optimeDurableDate: 2023-01-03T18:18:35.000Z,
      lastHeartbeat: 2023-01-03T18:18:43.290Z,
      lastHeartbeatRecv: 2023-01-03T18:18:44.510Z,
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: 'rs1:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 1,
      configTerm: 273
    },
    {
      _id: 2,
      name: 'rs3:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 490,
      optime: [Object],
      optimeDurable: [Object],
      optimeDate: 2023-01-03T18:18:35.000Z,
      optimeDurableDate: 2023-01-03T18:18:35.000Z,
      lastHeartbeat: 2023-01-03T18:18:43.273Z,
      lastHeartbeatRecv: 2023-01-03T18:18:43.452Z,
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: 'rs2:27017',
      syncSourceId: 1,
      infoMessage: '',
      configVersion: 1,
      configTerm: 273
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1672769915, i: 1 }),
    signature: {
      hash: Binary(Buffer.from("6b5aa5449f25c6da9495f373ab8b879da89ace3f", "hex"), 0),
      keyId: Long("7148292191616499713")
    }
  },
  operationTime: Timestamp({ t: 1672769915, i: 1 })
}
```

As you can see, rs1's type is RSSecondary inside of the errored container but it is showing as the Primary when checking rs.status().  
To reiterate, we are using Debian Bullseye-Slim(latest). We are not sure if Debian is having a DNS caching issue and haven't found any information that would suggest that would be the issue, or if this is an issue with Mongoose or the MongoDB driver.

**Comment by austinconry** [comment]
@vkarpov15 We tried to make a repo where this issue could be recreated but it's difficult for it to be recreated on a local computer.  

We created a reconnect logic for the Mongoose client so that if this error happens it disconnects Mongoose from Mongo and reconnects using the mongoose.connect() function.  Doing this reconnect fixed the containers that were receiving this error but this obviously means that the request that initially came through would not be fulfilled and every errored container would have to hit this retry logic meaning that multiple queries would fail.  This seems like an issue with the client that may be related to the DNS for rs1 no longer being resolvable when rs1 is down but we are still unsure.

[mongoose-replica-debug.zip](https://github.com/Automattic/mongoose/files/10340111/mongoose-replica-debug.zip)

**Comment by AustinMutschler** [comment]
This might be an issue with how Mongoose handles unresolvable DNS. In docker when a container goes down like rs1, that hostname is no longer resolvable. It could be possible that Mongoose is not handling this properly so that when rs1 comes back online and it's DNS is resolvable again it does not get the latest config.

**Comment by benhason1** [comment]
Anything new about it? 🙏

**Comment by austinconry** [comment]
@benhason1  The reconnect functionality mentioned earlier has allowed us to get past that error without it bringing down any of our servers or preventing them from making requests.  Other than that, we haven't found any other fixes for this issue.

**Comment by vkarpov15** [comment]
We haven't been able to repro this, haven't been able to successfully expose port 3000 for the backend-server image. We needed to make some changes to the docker-compose file to make it valid yml:

```
version: '3.3'

services:
  rs1:
    image: mongo:4.4.5
    command: mongod --replSet "rs0"
    networks:
      - mongo
    ports:
      - 27017:27017
    deploy:
      replicas: 1
    volumes:
      - rs1:/data/db 
      - rs1:/data/configdb
  rs2:
    image: mongo:4.4.5
    command: mongod --replSet "rs0"
    networks:
      - mongo
    deploy:
      replicas: 1
    volumes:
      - rs2:/data/db 
      - rs2:/data/configdb
  rs3:
    image: mongo:4.4.5
    command: mongod --replSet "rs0"
    networks:
      - mongo
    deploy:
      replicas: 1
    volumes:
      - rs3:/data/db 
      - rs3:/data/configdb
  rs:
    image: mongo:4.4.5
    command: mongo --host rs1 --eval 'rs.initiate({ _id:"rs0", version:1, members:[ { _id:0, host :"rs1", priority:100 }, { _id:1, host:"rs2", priority:2 }, { _id:2, host:"rs3", priority:2 } ] })'
    networks:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  backend-server:
    image: mongo-test-backend-server:latest
    deploy:
      replicas: 5
    ports:
      - 3000:3000
    networks:
      - mongo

volumes:
  rs1:
    driver: local
  rs2:
    driver: local
  rs3:
    driver: local

networks:
  mongo:
    driver: overlay
    driver_opts:
      encrypted: "true"
    internal: true
    attachable: true
```

Given that we aren't able to run the repro script, not much more we can do to debug. One alternative you can try is logging `serverHeartbeatSucceeded`, `serverHeartbeatFailed`, and `topologyDescriptionChanged` events as follows:

```javascript
'use strict';

const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/mongoose_test');

mongoose.connection.client.on('serverHeartbeatSucceeded', data => {
  console.log(new Date(), 'serverHeartbeatSucceeded', require('util').inspect(data, { depth: 10 }));
});

mongoose.connection.client.on('serverHeartbeatFailed', data => {
  console.log(new Date(), 'serverHeartbeatFailed', require('util').inspect(data, { depth: 10 }));
});


mongoose.connection.client.on('topologyDescriptionChanged', data => {
  console.log(new Date(), 'topologyDescriptionChanged', require('util').inspect(data, { depth: 10 }));
});
```

That will help provide more information as to why the MongoDB node driver thinks rs1 isn't the primary.
