### ISSUE TITLE
Mongoose validation fails when removing and updating simultaneously on array

### ISSUE THREAD

**Issue by neverfox** [Automattic/mongoose#2344]
I have a schema that involves a nest of arrays, with the final array storing objects that have a required field. When I try to update the whole top-level document (fund) such that I'm removing some of the objects in the bottom level array (holdings) while also changing the value of `allocation` on some of the objects I'm keeping, it fails the `required` validation. However, if I do it in two stages (either deleting the unwanted objects first with a save, then changing the others with a save; or vice versa), it works fine.

Here is the schema (simplified for clarity):

```
holdingSchema = new Schema
  instrument_id:
    type: Schema.ObjectId
    required: true
    ref: 'Instrument'
  allocation:
    type: Number
    required: true

positionSchema = new Schema
  holdings: [holdingSchema]

fundSchema = new Schema
  positions: [positionSchema]
```

For example, I have 11 items in holdings. I remove 3 and change the allocation value of another. I then set and save the whole fund document via JSON. This leads to a validation error. If I don't change the allocation value of any remaining items, all goes smoothly.

~~I can *add* and *change* in the same operation. I can *add* and *remove* in the same operation. I can even *add*, *change* and *remove* in the same operation. I just cannot *remove* and *change* (no add) in the same operation.~~ See below.

Is this a known limitation, forcing me to build a two-stage process or is there something wrong?

Mongoose 3.8.16
