### ISSUE TITLE
Hope to support find and filter by populate document.

### ISSUE THREAD

**Issue by KID-WuMeng** [Automattic/mongoose#4685]
I assume there are two schema:

```
BookSchema = new Schema({
    name: 
      type: String
    author:
      ref: 'Author'
})

AuthorSchema = new Schema({
    name:
      type: String
    region:
      type: String
})
```

And existed some data:

```
book1:
    name: '...'
    author: '...'
book2:
    name: '...'
    author: '...'
...

author1:
    name: '...'
    region: 'Asian'
author2:
    name: '...'
    region: 'Europe'
...
```

Now, I want to find the books be written by author from Asian and try the code:

```
Book.find().populate({
    path: 'author',
    match: {region: 'Asian'}
}).exec()
```

I seen the result is all books and some books from the non-asian author do not populate the author field. But according to my requirement, I hope the books which from non-asian author should be not found in result.

I see the question that tell me no-way to implement the requirement at stackoverflow:
[http://stackoverflow.com/questions/31357745/find-after-populate-mongoose](http://stackoverflow.com/questions/31357745/find-after-populate-mongoose)

Is there only find all data and filter in ``exec()`` ? If the data collection is large, it is a low-efficiency.

Can you support a new way or what is the best practice in this question ?
