### ISSUE TITLE
'MongoNetworkError: failed to connect to server' when connecting ReplicaSet

### ISSUE THREAD

**Issue by yokingma** [Automattic/mongoose#7153]
I set up a 3 node replica set server with docker, it works fine

myhost:27017 =>172.18.0.2:27017  
myhost:27018 =>172.18.0.3:27017  
myhost:27019 =>172.18.0.4:27017  

but get error when try to connect :
```
{ MongoNetworkError: failed to connect to server [172.18.0.2:27017] on first connect [MongoNetworkError: connection 5 to 172.18.0.2:27017 timed out]
```

code:
```
const mongoose = require('mongoose')  
const opt = {  
    authSource: 'admin',
    replicaSet: 'replicaset',
    useNewUrlParser: true
}  
const uri = 'mongodb://user:password@myhost:27017,myhost:27018,myhost:27019/dbname'  

mongoose.connect(uri, opt).then(function () {
    console.log('Mongodb connect success!')
}, function (err) {
    console.log('Mongodb connect error: ', err)
})  
```

if connecting without ReplicaSet , works fine:
```
const opt = {  
    authSource: 'admin',
    useNewUrlParser: true
}  
const uri = 'mongodb://user:password@myhost:27017/dbname'  
```

mongoDB: 4.0.3
node: v8.11.3
mongoose: 5.3.4

Please help to find the problem

Thanks!

**Comment by vkarpov15** [comment]
Make sure the host names that running rs.conf() outputs line up with the ones in your connection string as described here: https://mongoosejs.com/docs/connections.html#replicaset-hostnames . That should fix it.

**Comment by bertero** [comment]
Hi @vkarpov15, I read the link you sent and it was clear.

Even so my issue persists. Let me explain a little further:

## What I have up and running
I've set up three containers (using docker-compose) running one mongo process inside each. Then I've started the replica set, by connecting with one of them and running all the `rs.initialize()` process.

`docker-compose.yml`:
```yml
version: "3"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    restart: always
    volumes:
      - ./mongo0/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 127.0.0.1:27018:27017
    restart: always
    volumes:
      - ./mongo1/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 127.0.0.1:27019:27017
    restart: always
    volumes:
      - ./mongo2/data:/data/db
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
```

`start-replica-set.sh`:
```shell
docker exec -it mongo0 mongo --eval " \
db = (new Mongo('localhost:27017')).getDB('test') && \
rs.initiate({ \
\"_id\":\"rs0\", \
\"members\":[ \
{\"_id\":0,\"host\":\"mongo0:27017\"}, \
{\"_id\":1,\"host\":\"mongo1:27018\"}, \
{\"_id\":2,\"host\":\"mongo2:27019\"} \
]})
"
```

MongoDB `connectionURI` used to connect via `mongoose`:
```js
const connectionURI = 'mongodb://mongo0:27017,mongo1:27017,mongo2:27017/test?replicaSet=rs0
```

## The issue

When I run a local test (outside the docker env) and try to connect using the `connectionURI` above mentioned, I get the error:
`MongoNetworkError: failed to connect to server [mongo1:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo1 mongo1:27017`.

Do you have any suggestions to run a MongoDB replica set inside a docker env and connect to it via `mongoose` when running local tests outside docker?

Thanks in advance.
