### ISSUE TITLE
Weird unpredictable behaviour

### ISSUE THREAD

**Issue by mindrunner** [Automattic/mongoose#8942]
Not sure if this is the right place to post. I am a little bit out of ideas where this issue can origin from. I developed a Node/Express/Mongoose backend, with a quite small and straight forward Database part. There is only one model which looks more or less like this:
```
const mySchema = mongoose.Schema({
  url: { type: String, required: true },
  timestamp: { type: Date, default: null },
  o1: { type: Object, required: false },
  o2: { type: Object, required: false },
  o3: { type: Object, required: false },
  o4: { type: String, required: false },
  o5: { type: Object, required: false },
  o6: { type: Object, required: false },
  o7: { type: Object, required: false },
  o8: { type: Object, required: false },
  o9: { type: Object, required: false },
  o10: { type: Object, required: false },
  o11: { type: Object, required: false },
  o12:  {type: Object, required: false },
  o13: { type: Object, required: false },
});
```
The `create` endpoint gathers a quite big amount of different data and stores it in the `Object` properties:
```
  async insert (data) {
    let result = new mySchema(data);
    let options = {
      setDefaultsOnInsert: true,
      checkKeys: false,
    };
    await result.save(options);
    return result;
  }
}
```
To query one of this entries, I am using the mondodb internal `_id` property:
```
  async byId (id) {
    return await mySchema.findOne({ _id: id }).exec();
  }
```

I am developing the whole thing with webstorm, have a build pipeline which creates a docker container and on production, this is pretty much the setup:
```
version: '3.7'
services:
  backend:
    restart: always
    image: backend:latest
    volumes:
      - ./log:/app/log
    env_file:
      - .env-backend
    expose:
      - 3000
    depends_on:
      - mongodb

  frontend:
    restart: always
    image: frontend:latest
    expose:
      - 8080

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb:/data/db
```

Now comes the problem. It seems that mongodb is not reliably serving me the existing data. I have the following observations:

- Directly after inserting a document, a query `byId` returns null. Trying a second time it normally succeeds.
- There is another endpoint to return an array based on the `url` property:
```
  async byHostName (hostName) {
    return await mySchema.find({ url: hostName }).exec();
  }
```
Calling this multiple times in a row, sometimes returns different results. As far as my observations went, I usually have two alternating result arrays which are always the same if I repeat the procedure of calling the endpoint. If in this state, some of the `byId` requests return null, even though the id is 100% sure existing in the database.

I already refactored a lot of the code to make it more robust, stable, integrated proper logging, but I have no clue where the issue might be.

This only happens on the deployed production system. It never occurs locally and I could never reproduce it by connecting with my local dev-environment to the production database.

Also, I could not reproduce this behavior by spinning up the whole thing with docker-compose on my local system.

I previously assumed, there are some issues with indexed. I already wiped the whole database and cleanly imported the data into a fresh new one. No luck

I am lost. Calling out for help. Maybe someone has an idea.
