### ISSUE TITLE
mongose.save() block and doesn't do anything?

### ISSUE THREAD

**Issue by athina635** [Automattic/mongoose#9102]
I'm trying to use a very basic MongoDB method is to save a document on a database with mongoose.

1.I installed my MongoDB in centos 7

2.Create a database on the Mongo shell using: use mydatabase and insert a document inside it as normal.

3.Install mongoose and make a connection between my nodejs app and the MongoDB:

```
mongoose.connect('mongodb://localhost:27017/goClass_test', {
  useUnifiedTopology: true,
  useNewUrlParser: true,
});
```
4. test the connection and all is fine with:

```
db.once('open', () => {
  console.log('DB Connected');
});
```
Import the model schema as normal:

`var { Classe } = require('../DBModels/GoClassDBModels/classes');`

try to add new document like this:

```
var newClasse = new Classe({
     label: 'hello',
     level: 'level',
   });
newClasse.save()
```
My Model is:

```
const mongoose = require('mongoose');
const { Schema } = require('mongoose');
var ObjectId = mongoose.Schema.Types.ObjectId;

var classSchema = new Schema({
  directeurId: {
    type: ObjectId,
  },
  label: {
    type: String,
  },
  level: {
    type: String,
  },
  studentNbr: {
    type: String,
  },
});

var Classe = mongoose.model('Classes', classSchema);
module.exports = { Classe };
```

The problem is: nothing happened. No document has been inserted and no errors. Can you suggest to me, please?

**PS: I'm trying to request from an HTTP server without HTTPS.**

**will that affect my requests nd block the save to the database?**

**Comment by vkarpov15** [comment]
Where is your `mongoose.connect()` call? Can you make sure that's being called? It sounds like you're not connected to the database.

**Comment by abhinavsri360** [comment]
Hey @vkarpov15 I have the same issue i.e., .save() doesn't do anything can you help me out with that? Here, are my code snippets

__Mongoose connection__
```yaml
const dbOptions = {
  useNewUrlParser: true,
  useUnifiedTopology: true
}

const connection = mongoose.createConnection(process.env.DB_URL, dbOptions, () => { console.log('connected to db') })

const sessionStore = new MongoStore({ mongooseConnection: connection, collection: 'sessions' })

app.use(session({
  secret: process.env.SECRET,
  resave: false,
  saveUninitialized: true,
  store: sessionStore,
  cookie: {
    maxAge: 300
  }
}))
```

__User Schema__
```yaml
const mongoose = require('mongoose')

const UserSchema = new mongoose.Schema({
  username: {
    type: String,
    unique: true,
    required: true
  },
  hash: {
    type: String
  },
  salt: {
    type: String
  }
}, {
  timestamps: true
})

module.exports = mongoose.model('Users', UserSchema)
```

__Routing__
Herein code executes till creating hash and salt I tried using the console statements, but does nothing further.
```yaml
var express = require('express')
var router = express.Router()

const User = require('../models/User')
const passport = require('passport')
const genPassword = require('../passwordUtil').genPassword

/* GET users listing. */
router.get('/', async function (req, res) {
  try {
    const findusers = await User.find()
    res.json(findusers)
  } catch (err) {
    res.json({ message: err })
  }
})

router.post('/register', (req, res) => {
  const salthash = genPassword(req.body.password)

  const hash = salthash.hash
  const salt = salthash.salt

  const user = new User({
    username: req.body.username,
    hash: hash,
    salt: salt
  })

  try {
    const saveduser = user.save()
    res.json(saveduser)
  } catch (err) {
    res.json({ message: err })
  }
})

router.post('/login', passport.authenticate('local'), (req, res, next) => {})

module.exports = router
```


Also, Idk if this is required but here's my app.js file please let me know if you find anything wrong. In my opinion this one's healthy but just to be sure. Please review this and let me know.
__App.js__
```yaml
var createError = require('http-errors')
var express = require('express')
var path = require('path')
var cookieParser = require('cookie-parser')
var logger = require('morgan')

const mongoose = require('mongoose')
require('dotenv/config')
const bodyparser = require('body-parser')
const cors = require('cors')
const session = require('express-session')
const passport = require('passport')
const MongoStore = require('connect-mongo')(session)
require('./authenticate')

var indexRouter = require('./routes/index')
var usersRouter = require('./routes/users')

var app = express()

// view engine setup
app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'pug')

app.use(logger('dev'))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use(cookieParser())
app.use(express.static(path.join(__dirname, 'public')))

app.use(cors())
app.use(bodyparser.json())

const dbOptions = {
  useNewUrlParser: true,
  useUnifiedTopology: true
}

const connection = mongoose.createConnection(process.env.DB_URL, dbOptions, () => { console.log('connected to db') })

const sessionStore = new MongoStore({ mongooseConnection: connection, collection: 'sessions' })

app.use(session({
  secret: process.env.SECRET,
  resave: false,
  saveUninitialized: true,
  store: sessionStore,
  cookie: {
    maxAge: 300
  }
}))

app.use(passport.initialize())
app.use(passport.session())

app.use('/', indexRouter)
app.use('/api/users', usersRouter)

// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404))
})

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message
  res.locals.error = req.app.get('env') === 'development' ? err : {}

  // render the error page
  res.status(err.status || 500)
  res.render('error')
})

module.exports = app
```
